### ISSUE TITLE
single quotation problem at twitter

### ISSUE THREAD

**Issue by volanja** [volanja/ansible_spec#110]
`@aWebprogrammer` said:
ansible provisioner of vagrant export this.
```
ansible_user='user'
```

this idiom is not written on Ansible Doc.
According to Ansible Doc, should not use single single.

```
ansible_user=user
```

But `ansible-inventory` is cut out single quotation.
So,  `@aWebprogrammer` think that `ansible_spec` should cut out single quotation.

**Comment by volanja** [comment]
It seems that `@aWebprogrammer` will create other implementation.
So I closed it.

**Comment by sagiru** [comment]
Hi,

single quotation is not disallowed explicitly. The Ansible Docs talks about a INI-Like format and for INI it es explicit allowed to use single and double quotes. So i think thats why ansible handle it correctly. The other point that the non handling of this quotes breaks the rules about Robustness. Beside that you need the quotes for e.g. the ansible_ssh_private_key_file because there are whitespaces and other signs allowed and they has to be quoted (with single or double quotes).

Regards
sagiru
